apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucas-ht/lhutt-iot-manifests.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true