apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app-deploy-1
  labels:
    version: '1'
    app: iot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      containers:
      - name: iot-app
        image: l60039177/lhutt-iot-app1:1.0.0
        ports:
          - containerPort: 80
            name: iot-app-port