apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: post-sync-job
        image: busybox
        command: ["sh", "-c", "echo 'Post-sync job executed successfully' && sleep 30"]
      restartPolicy: Never
  backoffLimit: 0
